### ISSUE TITLE
IDEATION: Says 0 folders when there is 1.

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1223]
User makes folder and adds ideas, it only changes to say 1 folder when he refreshes.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/195634d6-b673-4807-aee3-8b0b443f74e1)

**Comment by ssin1901** [comment]
@BeccaMelhuish can you check the steps (see screen recording)?

https://github.com/citizenos/citizenos-fe/assets/72747107/127580cb-875a-405c-aa49-1b1fe3a9ee8b

Seems that the issue is solved.

**Comment by BeccaMelhuish** [comment]
@ssin1901 looks good from this recording, though in this case here it's still not quite right:

https://www.loom.com/share/78a2dd87ba484cb9bfcf38ea662709be?sid=ea35c984-4033-42cb-9cc8-88403f78322b

**Comment by ssin1901** [comment]
@BeccaMelhuish could not replicate this issue. Can I close it?

**Comment by BeccaMelhuish** [comment]
@ssin1901 still the same issue for me, see here:
Though @ilmartyrk is this one of those 'refreshing' issues that can't easily be fixed? 

https://www.loom.com/share/eaf7b5b45c7c42a78a6584daab2b956a?sid=b868acaf-7b8a-4b50-b7e1-9b6728836169

**Comment by BeccaMelhuish** [comment]
(Not a high priority though I think, they'll figure out that it's a bug so it shouldn't get in the way of anything)
