### ISSUE TITLE
INVITATIONS: Logged out clicks view without joining but doesn't see the button to join topic/group

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1894]
**What is the problem?**
_Tested in Google Chrome in Developer app in Dev app_

Logged out user clicks on View topic without joining (screenshot1) and is redirected to the topic but the button to join topic is missing (screenshot2)

![Image](https://github.com/user-attachments/assets/a2b1f0d0-29e3-413f-a6d5-5e1de7c517d0)

![Image](https://github.com/user-attachments/assets/eaea8f85-5af9-4194-a18a-844e08f43ed0)

Same for View group without joining (screenshot3, screenshot4)

![Image](https://github.com/user-attachments/assets/ac82f0c3-ed2c-4754-9572-ae772c226209)

![Image](https://github.com/user-attachments/assets/63b916c3-5106-4a77-80a7-e3bd96e98ce0) 

**Why is this a problem?**
User is missing the prompt to join the topic in logged out view. 

**Possible solution.**
Should be the same UX as for a logged in view (screenshot5)

![Image](https://github.com/user-attachments/assets/24896269-fef7-44aa-8021-bbf15baee26a)

**Comment by BeccaMelhuish** [comment]
@DiverVM putting this straight to in progress and assigning you as it's linked to #1376 
(@ssin1901 reminder to do it like that for such sub-issues, so they don't get left behind in no status :))

**Comment by DiverVM** [comment]
fixed. One thing to mention here -> when logged out:
- user clicks on join button
- logs in through popup
- appears on the same page, but not joined the topic/group automatically with login, user has to press button again.

This is due to some more complex fix we need to implement here, so let's have a separate issue here if needed

**Comment by ssin1901** [comment]
@DiverVM thanks for mentioning the test steps! To me, all seems fixed except that the user has to press the button again when logged in (as you mentioned).

I'll make a separate issue but here is the screen recording @BeccaMelhuish 

https://github.com/user-attachments/assets/4e3f48c1-6352-4235-99bd-49b11f7c82c0

**Comment by BeccaMelhuish** [comment]
Moving to ready for pre-live but mentioning this related issue still to be fixed: https://github.com/citizenos/citizenos-fe/issues/1900
