### ISSUE TITLE
Topic: Bug in text editing - edited bits smaller and on new line  

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#673]
I edited a topic description - edits in bold: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/501406e1-9711-446e-9f64-f4904c8d98c5)

This is what it looks like in the topic - bold bits are smaller and on a new line:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7fba9416-a1de-4f31-9bbe-4348cdc58779)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed now

**Comment by ssin1901** [comment]
Not fixed (screenshot attached)


![Image](https://github.com/citizenos/citizenos-fe/assets/72747107/3ac24877-c072-479c-a7c3-af0648afaa3a)

**Comment by ilmartyrk** [comment]
@ssin1901 fixed the font-size now too. Other than that it should be as in styles

**Comment by ssin1901** [comment]
@ilmartyrk still seems to be different font sizes (see screenshots)

<img width="1241" alt="Screenshot 2024-02-19 at 01 19 34" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c5ffe47a-a1fd-464e-9e28-a44742b4b64c">
