### ISSUE TITLE
Voting: Neutral option didn't appear

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#768]
User had selected neutral vote option, but it didn't appear in preview or when published. (He was adding a voting phase to a discussion topic, if relevant). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d8cd6c15-70d2-4c30-9c2e-63f470f67fbc)

**Comment by BeccaMelhuish** [comment]
Same in another test, veto and neutral were both selected but didn't appear: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/71d7161e-cbdc-4b42-b949-4d93bc188d99)

**Comment by BeccaMelhuish** [comment]
And in another one on Friday, so consistently not there :)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk will add high priority as it's a broken thing, but please remove if not the sort of thing you meant :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Not fixed I'm afraid, neutral option didn't appear in the test yesterday despite being selected: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b013aad5-6f3f-4b70-aa17-bf5ae2cbd639)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5976fb84-e7be-4027-b9be-65a50afb70a0)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e6da6057-aafd-45c0-a0f8-6c72f67e9a1d)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I could not replicate the issue

**Comment by ilmartyrk** [comment]
Can you add step by step overview what he/she did

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I tested it again both in the start voting dialog and create voting topic I could not replicate this issue, though I found that at some random times all options get lost, not sure what is happening there as seems to be related to the update response from the API. Made some changes that should make this work more stable.
