### ISSUE TITLE
Topic: Users still confused by 'Intro' and 'Topic text' (and dud info link in topic create flow) 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#847]
**Round 2 insight:** 

Following on from this Round 1 issue #694, there is still uncertainty around the 'Intro'. All 4 users who set up topics expressed something about this - 2 that it didn't seem necessary, and 2 that they were confused what to put there. 

One tried clicking this link on that page hoping for guidance on what we expect to go in which bit. But this is a dead link: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8d5d6dc5-684f-482e-b50f-aeb8b35e23ea)

**Suggestions:** 
- Should we have some help buttons here with texts explaining what goes where? 
- Should we make Intro optional (currently it has a mandatory asterisk, those seems not to be technically enforced)? 
- Should we either remove the dud link, or put some guidance there? 
- We can keep an eye on this and decide whether to remove the intro at all?

**Comment by kevincrepin** [comment]
Could make it optional, but on the other hand it can also be a decision to make people think how they can introduce this topic for their readers... But yeah I think maybe not making it mandatory can remove some annoyances.

We can also take this approach that when you open it (not before) there's this help text:
![Screenshot 2024-02-22 at 11 38 29](https://github.com/citizenos/citizenos-fe/assets/26792281/7451a4e9-c029-485f-aac6-0508b285eb8b)


And definitely the link should work :)

**Comment by BeccaMelhuish** [comment]
Yes I think let's not make it mandatory - I see that you can no longer continue without adding one, but I don't think we should force it seeing as it's not always useful/necessary :) 

@kevincrepin I'm thinking maybe a one of the tooltip type help text's might work better though, as they are wondering what it is before they've clicked in it, or deciding they don't see the need so will skip it without clicking in it. So the tooltip would show them there is some guidance to help them more quickly :) 

For the text when it's added though, I think let's call them participants though not readers, so 'easier for participants to'.  

Re the dud link, I think let's just remove it for now seeing as we won't have a HC initially (so have nothing to link to), but then add it in when we do :)

**Comment by kevincrepin** [comment]
Ok sure, we can have the tooltip next to it:
![Screenshot 2024-02-27 at 14 58 50](https://github.com/citizenos/citizenos-fe/assets/26792281/a3653d0e-6b0a-4cfe-8ab1-8d2317b1c68f)

**Comment by BeccaMelhuish** [comment]
Ok great, thank you! 

So @ilmartyrk text would be what Kevin had above but with 'easier for participants to' rather than readers :) 

Will add pre-UX test label as would be great to have before next admin test (mobile) - hopefully Thurs at noon.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted an update

**Comment by BeccaMelhuish** [comment]
@ilmartyrk same line needs to be taken out of voting create flow too :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/909cf50b-40c8-46d3-a281-543b448fb4cf)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk On mobile is also still showing for discussion topics. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/111d4ea3-20d6-4c17-a1fa-dbcc95a04e23)

**Comment by BeccaMelhuish** [comment]
Same for groups creation flow:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/97ab6dd2-068d-402a-820a-1d7e4bdf5843)

**Comment by ssin1901** [comment]
Tested and there is still a dead link (screenshot1)
<img width="1296" alt="Screenshot 2024-03-03 at 21 52 15" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1dd22c3e-f878-4124-979a-41e95bd601ec">

However intro has been resolved (see screenshot2)
<img width="1226" alt="Screenshot 2024-03-03 at 21 54 28" src="https://github.com/citizenos/citizenos-fe/assets/72747107/80140391-bbfa-49f7-ab27-9eb8fa408169">

**Comment by BeccaMelhuish** [comment]
@ilmartyrk it still shows up in preview of create flow for both discussions and voting topics :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7060b4df-b853-4559-b6a7-13a2bb116f24)

**Comment by ssin1901** [comment]
Marked high priority due to the broken link
